### ISSUE TITLE
Meeting notes/minutes in HackMD

### ISSUE THREAD

**Issue by maddhruv** [nodejs/community-committee#315] opened 2018-05-15 05:29 UTC
NF has been using Google Docs for its minute's note-taking obviously for several reasons - collaborative and can be saved in Google Drive (hehe :smile_cat: )

[HackMD](https://hackmd.io) provides better features and most importantly it is for **MARKDOWN**
we can
- add new notes
- invite people
- download as markdown/HTML
- export to Dropbox/Google Drive/ Gist
- also can Publish the notes (with which, we don't have to add the meeting notes into the repository for records, else we can refer to the published link simply)

The **Free Plan** is itself reliable and sufficient for our purpose but also they have recently introduced  an Enterprise Plan that provides private SaaS

**Comment by maddhruv** [comment] 2018-05-15 16:45
They don't have an API as of now!
We(admin) has to manually create a note and later on publish it

Dont feel it is hard for the meeting chairrperson

**Comment by Tiriel** [comment] 2018-05-15 20:40
Tha platform seems really nice and feature-rich. I'd go for switching, if it wasn't for the lack of automation API. As @mhdawson said, it would feel like a regression.

But I must say, the ease it would put into creating the notes PR makes me hesitate. So I'm not all for it, but not all against either.

(That was the useful contribution of the day, kindly provided by your servant.)

**Comment by chowdhurian** [comment] 2018-05-15 21:00
This is the first I've learned that we've been using the API to create minutes docs. 😅 No big deal, since I don't PR minutes very often, and I didn't feel put upon.

**Comment by Tiriel** [comment] 2018-05-16 08:27
@chowdhurian The problem of using an API is not with PRing the minutes, but to automatically create the minutes doc which we use during the meetings.

The current tool created by @mhdawson uses GDoc API to create a document and populate it with a template, gets the link to that doc, and puts it into the issue it creates automatically for each meeting.
That's the automation we would be losing.

And while it may not seem the heaviest load in the world for us, I think manually creating the doc on an external platform for every meeting must indeed become a real hassle for the chair/secretary real quick.

So again, I quite like this platform, I tested it a bit and it works damn well, but I won't say a definitive yes/no for now.

**Comment by mhdawson** [comment] 2018-05-16 22:16
We could make the tool have an option not to create the google doc, but for any of the meetings, I chair I would not move over as I don't find getting the completed doc over to markdown to be enough of a problem to be worth having to manually create the doc in the first place.

**Comment by maddhruv** [comment] 2018-05-24 15:51
@mhdawson 
perhaps this could help https://github.com/hackmdio/hackmd/pull/673

**Comment by WaleedAshraf** [comment] 2018-06-24 10:51
Any update on this issue?

**Comment by mhdawson** [comment] 2018-06-25 21:46
I don't have any cycles to push this forward and I don't find the current approach an issue for the meetings I'm helping to moderate.

The net is that I won't get to this any time in the foreseeable future, if somebody wants to add an option to https://github.com/mhdawson/create-node-meeting-artifacts so that based on the config you can have it create the minutes using hackmdio instead of a google doc I'd be happy to take a PR.

**Comment by bnb** [comment] 2018-09-05 20:11
Going to close this for now. Feel free to re-open if you feel it's needed 👍

**Closed by bnb** 2018-09-05 20:11 UTC
