### ISSUE TITLE
Move Node Together Repo as an org under CommComm

### ISSUE THREAD

**Issue by rachelnicole** [nodejs/community-committee#63] opened 2017-05-24 21:20 UTC
Hey everyone, 

As I'm trying to re-organize Node Together so it can start happening again we've been trying to figure out a way for it to be a viable organization. Either that means becoming an entity and soliciting money from sponsorship, or trying to become a part of the Node Foundation org. 

I think the latter would be the easiest and smoothest, and potentially best way to get valuable input from people in the community on beginner education & outreach to underrepresented minorities.

I would love for it to live under the jurisdiction of CommComm, as I feel that we're best geared towards the basic principals that Node Together stands for, thanks to the great mission @ashleygwilliams put together in founding it.

I'd like to propose we have a discussion / vote during the meeting on whether or not to move forward with the process. 

@hackygolucky can provide a bit more insight to the viability of these options, as it's something she previously looked into last fall before I was brought on as the new organizer.

**Comment by hackygolucky** [comment] 2017-05-24 21:25
This is the first step! I tried to walk through a scenario where this would also require approval from the Node.js Foundation Board, but I can't think of it. Their input is generally needed for allocations or bylaws, yes? 

I imagine this is pretty similar in nature to what Code + Learn is for the CTC. The scenario that was recommended to me by @MylesBorins was CommComm-->Education-->NodeTogether.

**Comment by nebrius** [comment] 2017-05-24 21:54
My understanding is that as long as what we're bringing into CommComm fits under our responsibilities [as listed in our charter](https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md#section-5-responsibilities-of-the-cc) then we don't need board approval.

Reading through the list though, I don't think this fits in with the existing list, but education _definitely_ should be on the list IMO. It was just an oversight on our part.

I think we'll need to make a change to the charter to get "education initiatives" listed first (which does require board approval), and then we can bring this in without needing board approval.

We also have https://github.com/nodejs/community-committee/pull/50 open, which is another charter change, so we already have some things we need to bring to the board. I don't think it should be that much harder to make this charter change too.

I'll add a blurb about education in the existing PR to make it easier for the board to review the charter changes.

**Comment by gr2m** [comment] 2017-05-25 20:24
just fyi: this is currently not on the meeting agenda, shall we add it? https://docs.google.com/document/d/1J14T5lXuFWsaTqfkpmPruAZ4E-WsVe2V5TAaKwDjHN0/edit

**Comment by rachelnicole** [comment] 2017-05-25 20:26
@gr2m yes please

**Comment by hackygolucky** [comment] 2017-06-08 17:51
Hey all, as far as I can recall, the Board confirmed at the last meeting that they don't need a resolution for this on their end, but that Director @ashleygwilliams had brought up we should have legal review the guidelines documented for accepting students into each class to ensure we(NodeTogether) are doing everything in an acceptable fashion.

**Comment by hackygolucky** [comment] 2017-08-03 16:21
To make sure y'all feel comfortable with how this is being done, can we talk through the process of the file copy/transfer for this on our meeting today? cc @ashleygwilliams @rachelnicole @nebrius I'd like to make sure we are crystal clear so everyone is 👍

**Comment by nebrius** [comment] 2017-08-15 00:25
I'm removing the `cc-agenda` label for now because we have action items on next steps and are waiting for those to be done. We can re-add the label once the repos have been moved over, if need be.

**Comment by abreuretto** [comment] 2019-09-08 22:07
[Know my App Node CRUD API Generator to MySQL](https://github.com/abreuretto/NodeApiGenerator)

**Comment by bnb** [comment] 2019-12-25 19:07
Since this does not seem to be happening, going to close the issue for now. Will re-open at the point when we're ready to do the work.

**Closed by bnb** 2019-12-25 19:07 UTC
