### ISSUE TITLE
Closing issues or create a `pending` label

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#308] opened 2018-05-11 07:32 UTC
In the spirit of labeling `good-first-issues` 😃  in the repos, most issues in the CommComm repo has been open for a while with no activity. 

Please @nodejs/community-committee members, review issues, make contributions or discussion to either add `pending` or labels that fit the issue or close them to assist people coming into the ecosystem to know their way around. 👍

**Comment by Tiriel** [comment] 2018-06-06 09:40
This is indeed a real issue, there are lots of open issues with no activity (ironically, including this one).

I don't know whether a `pending` label would be of use though. In an ideal world, an open issue means there is still work to be done, and not-actionable /finished issues should be closed. We need to be more reactive on this.

cc @nodejs/community-committee 
Without response or input on the label idea in 72hours, I'll close this issue.

**Comment by WaleedAshraf** [comment] 2018-06-06 09:46
Instead of marking an issue as pending, it'd be good to close it and reopen when/if needed. And pending label will cause more issue-satling.

**Comment by Bamieh** [comment] 2018-06-06 11:05
most of the opened issues date back from march, which is not a long period at all. the remaining 10-15 issues are opened because they still need attention and resolution (but not an immediate one). I do not see this as a problem in this repo, 40 issues and 25 of them date maximum a few months ago is more than a acceptable IMO.

**Comment by Tiriel** [comment] 2018-06-06 11:09
It's true that the question is more to know if the issue is actionable or not and not its date of opening. But we could indeed do a bit more on the cleaning side to avoid stale issues IMHO.

**Comment by bnb** [comment] 2018-06-11 14:33
For what it's worth, I do try to go through our backlog once every month or two to close older issues/ask if progress has been made. This isn't a responsibility of the CommComm chair, but something I've personally found is helpful for maintaining an ongoing and constructive discussion long-term. [Here's](https://github.com/nodejs/community-committee/issues/46#issuecomment-334306306) an example of that.

Having more people help with this kind of work across all the CommComm repos would definitely be appreciated 🙌

**Comment by codeekage** [comment] 2018-07-21 07:49
I have gone through the @nodejs/community-committee repo and here is a list of issues I think that should be closed or revisited.

#353
#341
#337
#331
#309
#275
#268
#267
#299
#313

That’s all for now. I will be closing them in 72 hours of inactivity. :smile: :praying:

**Comment by hackygolucky** [comment] 2018-07-26 16:42
Can we see this as a PR to the [Collaborator Guide?](https://github.com/nodejs/community-committee/blob/master/COLLABORATOR_GUIDE.md#nodejs-collaborator-guide). Particularly 
1. the process we've documented here
2. making sure we comment on every issue before it is closed having followed this process so that  contributors understand why it was closed and that it can easily be reopened.

**Comment by TimothyGu** [comment] 2018-08-18 23:04
@codeekage Maybe you could go ahead and close them now? Many 72 hours have passed :)

**Closed** 2018-11-29 12:36 UTC
